# Generated by Django 6.0.4 on 2026-04-30 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goal', models.CharField(choices=[('weight_loss', 'Emagrecimento'), ('hypertrophy', 'Hipertrofia'), ('maintenance', 'Manutenção'), ('general_health', 'Saúde geral')], default='general_health', max_length=20)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentário'), ('light', 'Levemente ativo'), ('moderate', 'Moderadamente ativo'), ('intense', 'Muito ativo'), ('very_intense', 'Extremamente ativo')], default='sedentary', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('professional_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
