# Generated by Django 6.0.4 on 2026-04-30 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet', '0001_initial'),
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('cancelled', 'Cancelado')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='diet.mealplan')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_assignments', to='professional.professionallink')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_assignments', to='professional.professionallink')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workouts.workout')),
            ],
        ),
        migrations.AddConstraint(
            model_name='professionallink',
            constraint=models.UniqueConstraint(fields=('student', 'professional'), name='unique_student_professional_link'),
        ),
        migrations.AddConstraint(
            model_name='mealplanassignment',
            constraint=models.UniqueConstraint(fields=('link', 'meal_plan'), name='unique_meal_plan_assignment'),
        ),
        migrations.AddConstraint(
            model_name='workoutassignment',
            constraint=models.UniqueConstraint(fields=('link', 'workout'), name='unique_workout_assignment'),
        ),
    ]
