# Generated by Django 6.0.4 on 2026-07-02 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(max_length=6, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativo'), ('revoked', 'Desvinculado')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_links', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_assignments', to='professional.professionallink')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workouts.workout')),
            ],
        ),
        migrations.AddIndex(
            model_name='professionallink',
            index=models.Index(fields=['student', 'status'], name='professiona_student_c70dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='professionallink',
            index=models.Index(fields=['professional', 'status'], name='professiona_profess_d2d376_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutassignment',
            index=models.Index(fields=['link', 'is_active'], name='professiona_link_id_d292ab_idx'),
        ),
    ]
