# Generated by Django 6.0.4 on 2026-07-03 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_seed_taco_foods'),
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_assignments', to='professional.professionallink')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='diet.mealplan')),
            ],
            options={
                'indexes': [models.Index(fields=['link', 'is_active'], name='professiona_link_id_eb90bd_idx')],
            },
        ),
    ]
